ci(github actions): consolidate workflows

diff --git a/.github/workflows/version/version.yml b/.github/workflows/version/version.yml
--- a/.github/workflows/version/version.yml
+++ b/.github/workflows/version/version.yml
@@ -1,4 +1,4 @@
-name: Version On Merge v2
+name: Version
 concurrency:
   group: ${{ github.workflow }}-${{ github.ref }}-versioning
 on:
@@ -23,9 +23,10 @@ jobs:
           clientId: ${{ secrets.APP_CLIENT_ID }}
           clientSecret: ${{ secrets.APP_CLIENT_SECRET }}
           userRefreshToken: ${{ secrets.USER_REFRESH_TOKEN }}
-  call-verify-commit:
+  verify-commit:
     if: ${{ github.event.pull_request.merged == true }}
-    uses: ./.github/workflows/verify-commit.yml
+    needs: [check-tokens]
+    uses: ./.github/workflows/version/verify-commit.yml
   version-patch:
     if: ${{ github.event.pull_request.merged == true }}
     needs: [call-verify-commit, check-tokens]
@@ -153,3 +154,26 @@ jobs:
       - run: |
           echo "::notice:: skip versioning because we are not deploying"
           exit 0
+  check-version-job:
+    runs-on: ubuntu-latest
+    needs:
+      [
+        check-tokens,
+        verify-commit,
+        version-patch,
+        version-minor,
+        version-major,
+        skip-no-deploy,
+      ]
+    if: ${{ always() }}
+    steps:
+      - run: |
+          if [[ '${{ needs.check-tokens.result }}' == 'failure' && '${{ needs.veriy-commit.result }}' == 'failure' && '${{ needs.version-patch.result }}' == 'failure' && '${{ needs.version-minor.result }}' == 'failure' && '${{ needs.version-major.result }}' == 'failure' && '${{ needs.skip-no-deploy.result }}' == 'failure' ]]; then
+            echo "Version Failed"
+            exit 1
+          elif [[ '${{ needs.version-patch.result }}' == 'success' || '${{ needs.version-minor.result }}' == 'success' || '${{ needs.version-major.result }}' == 'success' || '${{ needs.skip-no-deploy.result }}' == 'success' ]]; then
+            echo "Version Succeeded"
+            exit 0
+          else
+            exit 1
+          fi
