Token Action (#224)
* fix(secrets): fix call to secret service pt. 1

* Angular CLI update for packages - @angular/cdk@*, @angular/material@*

* feat(cloud functions): upgrade to FB CFv2

migration to firebase cloud functions v2

BREAKING CHANGE: refer to
https://firebase.google.com/docs/functions/2nd-gen-upgrade?hl=en&authuser=0

* fix(cloud functions): add .value to secret params

* refactor(cloud functions): update code to match secret service changes

* style(lint): add lint fixes

* feat(auth): add foundation for auth service

BREAKING CHANGE: users will only be able to use certain features when authenticated

#114

* style(lint): add eslint ignores for lifecycle methods

* refactor(cloud functions): update secret service url

* fix(about me): fix link to UPE induciton

* build(environment): update dev env file

* feat(auth): add more specific typings

#114

* meh

* m

* ci: mkk

* feat(github actions): add new action for getting tokens

#111

* ci(github-actions): finalize new token update tokens action setup

#111

---------

Signed-off-by: Jake Z <10226084+Zwiqler94@users.noreply.github.com>
Co-authored-by: Zwiqler94 <Zwiqler94@users.noreply.github.com>

diff --git a/.github/workflows/main-workflow.yml b/.github/workflows/main-workflow.yml
--- a/.github/workflows/main-workflow.yml
+++ b/.github/workflows/main-workflow.yml
@@ -4,8 +4,7 @@ concurrency:
   cancel-in-progress: true
 on:
   pull_request_target:
-    branches:
-      ['*', 'development','main']
+    branches: ["*", "development", "main"]
     types:
       - opened
       - closed
@@ -15,50 +14,52 @@ permissions:
   pages: write
   id-token: write
 jobs:
-  test:
-    name: mm
+  analyze-code:
+    uses: ./.github/workflows/codeql-analysis2.yml
+  version:
+    needs: ["analyze-code"]
+    uses: ./.github/workflows/version-on-merge.yml
+    secrets: inherit
+  deploy-dev-pr-preview:
+    needs: ["analyze-code", "version"]
+    if: ${{ (github.event.action == 'synchronize' || github.event.action == 'opened')  && github.base_ref == 'development' }}
+    uses: ./.github/workflows/firebase-hosting-pull-request-development.yml
+    secrets: inherit
+  deploy-prod-pr-preview:
+    needs: ["analyze-code", "version"]
+    if: ${{ (github.event.action == 'synchronize' || github.event.action == 'opened') && github.base_ref == 'main' }}
+    uses: ./.github/workflows/firebase-hosting-pull-request.yml
+    secrets: inherit
+  deploy-dev:
+    needs: ["analyze-code", "version"]
+    if: ${{ (github.event.action == 'synchronize' || github.event.action == 'opened')  && github.base_ref == 'development'}}
+    uses: ./.github/workflows/firebase-hosting-merge-development.yml
+    secrets: inherit
+  deploy-prod:
+    needs: ["analyze-code", "version"]
+    if: ${{ (github.event.action == 'synchronize' || github.event.action == 'opened') && github.base_ref == 'main' }}
+    uses: ./.github/workflows/firebase-hosting-merge.yml
+    secrets: inherit
+  check-deploy-job:
     runs-on: ubuntu-latest
+    needs:
+      [
+        "analyze-code",
+        "version",
+        "deploy-dev-pr-preview",
+        "deploy-prod-pr-preview",
+        "deploy-dev",
+        "deploy-prod",
+      ]
+    if: ${{ always() }}
     steps:
-      - name: a
-        uses: Zwiqler94/GH-Actions@v0.2.0
-    
-  # analyze-code:
-  #   uses: ./.github/workflows/codeql-analysis2.yml
-  # version:
-  #   needs: ["analyze-code"]
-  #   uses: ./.github/workflows/version-on-merge.yml
-  #   secrets: inherit
-  # deploy-dev-pr-preview:
-  #   needs: ["analyze-code", "version"]
-  #   if: ${{ (github.event.action == 'synchronize' || github.event.action == 'opened')  && github.base_ref == 'development' }}
-  #   uses: ./.github/workflows/firebase-hosting-pull-request-development.yml
-  #   secrets: inherit
-  # deploy-prod-pr-preview:
-  #   needs: ["analyze-code", "version"]
-  #   if: ${{ (github.event.action == 'synchronize' || github.event.action == 'opened') && github.base_ref == 'main' }}
-  #   uses: ./.github/workflows/firebase-hosting-pull-request.yml
-  #   secrets: inherit
-  # deploy-dev:
-  #   needs: ["analyze-code", "version"]
-  #   if: ${{ (github.event.action == 'synchronize' || github.event.action == 'opened')  && github.base_ref == 'development'}}
-  #   uses: ./.github/workflows/firebase-hosting-merge-development.yml
-  #   secrets: inherit
-  # deploy-prod:
-  #   needs: ["analyze-code", "version"]
-  #   if: ${{ (github.event.action == 'synchronize' || github.event.action == 'opened') && github.base_ref == 'main' }}
-  #   uses: ./.github/workflows/firebase-hosting-merge.yml
-  #   secrets: inherit
-  # check-deploy-job:
-    # runs-on: ubuntu-latest
-    # needs: [ "analyze-code", "version", "deploy-dev-pr-preview", "deploy-prod-pr-preview", "deploy-dev", "deploy-prod"]
-    # if: ${{ always() }}
-    # steps:
-      # - run: |
-      #     if [[ '${{ needs.deploy-dev-pr-preview.result }}' == 'failure' && '${{ needs.deploy-prod-pr-preview.result }}' == 'failure' && '${{ needs.deploy-dev.result }}' == 'failure' && '${{ needs.deploy-prod.result }}' == 'failure' ]]; then
-      #        echo "Deploy Failed"
-      #        exit 1
-      #     elif [[ '${{ needs.deploy-dev-pr-preview.result }}' == 'success' || '${{ needs.deploy-prod-pr-preview.result }}' == 'success' || '${{ needs.deploy-dev.result }}' == 'success' || '${{ needs.deploy-prod.result }}' == 'success' ]]; then
-      #        exit 0
-      #     else
-      #       exit 1
-      #     fi
+      - run: |
+          if [[ '${{ needs.deploy-dev-pr-preview.result }}' == 'failure' && '${{ needs.deploy-prod-pr-preview.result }}' == 'failure' && '${{ needs.deploy-dev.result }}' == 'failure' && '${{ needs.deploy-prod.result }}' == 'failure' ]]; then
+             echo "Deploy Failed"
+             exit 1
+          elif [[ '${{ needs.deploy-dev-pr-preview.result }}' == 'success' || '${{ needs.deploy-prod-pr-preview.result }}' == 'success' || '${{ needs.deploy-dev.result }}' == 'success' || '${{ needs.deploy-prod.result }}' == 'success' ]]; then
+             exit 0
+          else
+            exit 1
+          fi
+
